// src/pages/api/clients/clientApi.ts
import { supabase } from '../../../lib/supabase'; // Adjust path as needed
import { Client, UUID } from '../../../types/database'; // Import Client and UUID types

export const clientApi = {
  /**
   * Fetches a client by their mobile number.
   */
  getClientByMobile: async (mobile: string): Promise<Client | null> => {
    const { data, error } = await supabase
      .from('clients')
      .select('*')
      .eq('mobile', mobile)
      .single(); // Use single() to expect one record or null

    if (error && error.code !== 'PGRST116') { // PGRST116 means no rows found, which is not an error for this check
      console.error('Error fetching client by mobile:', error);
      throw new Error(error.message);
    }
    return data as Client | null;
  },

  /**
   * Creates a new client.
   */
  createClient: async (newClientData: Omit<Client, 'id' | 'created_at' | 'updated_at' | 'qr_code' | 'points' | 'points_expiry' | 'discounted'>): Promise<Client> => {
    // Supabase will automatically generate 'id', 'created_at', 'updated_at'
    // 'points', 'points_expiry', 'discounted' have default values in DB
    const { data, error } = await supabase
      .from('clients')
      .insert([
        {
          name: newClientData.name,
          mobile: newClientData.mobile,
          email: newClientData.email,
          sms_opt_in: true, // Default to true as per requirement
          // qr_code is generated by a database function/default, no need to insert here
        }
      ])
      .select()
      .single();

    if (error) {
      console.error('Error creating client:', error);
      throw new Error(error.message);
    }
    return data as Client;
  },

  /**
   * Fetches a client by ID.
   */
  getClientById: async (id: UUID): Promise<Client | null> => {
    const { data, error } = await supabase
      .from('clients')
      .select('*')
      .eq('id', id)
      .single();

    if (error && error.code !== 'PGRST116') {
      console.error('Error fetching client by ID:', error);
      throw new Error(error.message);
    }
    return data as Client | null;
  }
};
